# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea5e9ff6fc0f55fd11cc10dec3ad6c3b0a3842327845812ff75fb2caaa9b5e2c26b377b74693ba225b1cac7f6ce8d337a4779d406df0251bc9960c3521c2114

test:
  secret_key_base: 772cb2d3bc00dad6bb3d32dbee9fee0729538b295f1fda73a043e8856519de9c227aa3d135ee443ff1ecf76539bccbab5bf7d307d7bcbd8f483c8144079bc3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
